import React, { useState } from "react";
import {
  Box,
  Grid,
  Typography,
  Paper,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Link,
} from "@mui/material";
import { styled } from "@mui/system";
import DescriptionIcon from "@mui/icons-material/Description";
import NoteIcon from "@mui/icons-material/Note";
import VerifiedIcon from "@mui/icons-material/Verified";
import VideoLibraryIcon from "@mui/icons-material/VideoLibrary";
import BuildIcon from "@mui/icons-material/Build";
import PhoneAndroidIcon from "@mui/icons-material/PhoneAndroid";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import GitHubIcon from "@mui/icons-material/GitHub";
import TwitterIcon from "@mui/icons-material/Twitter";
import FacebookIcon from "@mui/icons-material/Facebook";

const Item = styled(Paper)(({ theme }) => ({
  padding: theme.spacing(2),
  textAlign: "center",
  color: theme.palette.text.secondary,
  cursor: "pointer",
}));

const data = [
  {
    icon: <DescriptionIcon fontSize="large" />,
    title: "About Us",
    describe: `In the dynamic landscape of sustainable energy, our innovative solar energy app web page stands as a beacon of progress and efficiency. As the world increasingly pivots towards eco-friendly solutions, harnessing the power of the sun has never been more crucial. Our platform takes center stage, offering a sophisticated and user-friendly experience in the realm of solar panel placement simulations
Unveiling the Power of Simulation:Embark on a journey of precision and optimization with our state-of-the-art solar panel placement simulations. Designed as an effective tool for both novices and experts in the field, our platform allows you to visualize, plan, and perfect your solar energy projects with unparalleled accuracy.
The Green Revolution Unleashed:As the demand for clean and natural energy skyrockets, our web-based simulation tool emerges as a game-changer in the realm of sustainable energy. We understand the pivotal role solar energy plays across various sectors, and our simulation technology empowers you to contribute to the green revolution seamlessly.
Key Features That Set Us Apart:
Intuitive Design: Navigate effortlessly through our user-friendly interface, tailored to meet the needs of both seasoned professionals and those new to solar energy projects.
Optimization Capabilities: Maximize the efficiency of your solar energy projects by experimenting with various panel placements and configurations, ensuring you harness the sun's power to its fullest potential.
Data-Driven Insights: Benefit from in-depth analyses and comprehensive reports generated by our simulations. Make informed decisions backed by reliable data to elevate the success of your projects.
Real-Time Visualization: Witness the impact of different parameters on solar panel performance in real-time. Our platform allows you to see the immediate effects of your choices, enabling swift adjustments for optimal results.
Why Choose Our Solar Energy App Web Page?
Commitment to Sustainability: Join us in our commitment to a sustainable future. By utilizing our platform, you actively contribute to reducing the carbon footprint and advancing environmentally friendly practices.
Versatility Across Industries: Whether you're a researcher, a professional in the solar energy sector, or an environmental sustainability advocate, our platform caters to a diverse audience, making it a valuable resource for all.
Innovation at Your Fingertips: Stay ahead of the curve with our cutting-edge technology. We continuously update our platform to incorporate the latest advancements in solar energy, ensuring you always have access to the most innovative tools.
In conclusion, our solar energy app web page is not just a simulation platform; it's a gateway to a sustainable future. Join us in revolutionizing the way solar energy projects are designed and optimized. Empower yourself with the tools needed to make a lasting impact in the field of clean energy production.
Experience the future of solar energy simulation—where precision meets sustainability. Visit our website today and be a part of the green energy revolution!`,
  },
  {
    icon: <NoteIcon fontSize="large" />,
    title: "Contact Us",
    describe: (
      <>
        <Box display="flex" alignItems="center" mb={1}>
          <LinkedInIcon />
          <Link
            href="https://www.linkedin.com/in/berkay-avcı-126653269/"
            target="_blank"
            rel="noopener noreferrer"
            ml={1}
          >
            Berkay Avcı
          </Link>
        </Box>
        <Box display="flex" alignItems="center" mb={1}>
          <LinkedInIcon />
          <Link
            href="https://www.linkedin.com/in/yunus-emre-görgü-b75135239/"
            target="_blank"
            rel="noopener noreferrer"
            ml={1}
          >
            Yunus Emre Görgü
          </Link>
        </Box>
        <Box display="flex" alignItems="center" mb={1}>
          <LinkedInIcon />
          <Link
            href="https://www.linkedin.com/in/erhan-özalp/"
            target="_blank"
            rel="noopener noreferrer"
            ml={1}
          >
            Erhan Özalp
          </Link>
        </Box>
        <Box display="flex" alignItems="center" mb={1}>
          <LinkedInIcon />
          <Link
            href="https://www.linkedin.com/in/yunus-emre-arslan-3234571b4/"
            target="_blank"
            rel="noopener noreferrer"
            ml={1}
          >
            Yunus Emre Arslan
          </Link>
        </Box>
      </>
    ),
  },
  {
    icon: <VerifiedIcon fontSize="large" />,
    title: "Social",
    describe: (
      <>
        <Box display="flex" alignItems="center" mb={1}>
          <GitHubIcon />
          <Link
            href="https://github.com/CankayaUniversity/ceng-407-408-2023-2024-Solar-Energy-Application/wiki"
            target="_blank"
            rel="noopener noreferrer"
            ml={1}
          >
            GitHub
          </Link>
        </Box>
        <Box display="flex" alignItems="center" mb={1}>
          <TwitterIcon />
          <Link href="#" target="_blank" rel="noopener noreferrer" ml={1}>
            Twitter
          </Link>
        </Box>
        <Box display="flex" alignItems="center" mb={1}>
          <FacebookIcon />
          <Link href="#" target="_blank" rel="noopener noreferrer" ml={1}>
            Facebook
          </Link>
        </Box>
      </>
    ),
  },
  { icon: <VideoLibraryIcon fontSize="large" />, title: "How to Use" },
  { icon: <BuildIcon fontSize="large" />, title: "Frequently Asked" },
  { icon: <PhoneAndroidIcon fontSize="large" />, title: "My SolarApp" },
];

const BlogLink = () => {
  const [open, setOpen] = useState(false);
  const [selectedItem, setSelectedItem] = useState(null);

  const handleClickOpen = (item) => {
    setSelectedItem(item);
    setOpen(true);
  };

  const handleClose = () => {
    setOpen(false);
  };

  return (
    <Box sx={{ flexGrow: 1, padding: 4 }}>
      <Typography variant="h4" gutterBottom align="center" color="primary">
        Featured Resource & Support Topics
      </Typography>
      <Grid container spacing={3} justifyContent="center">
        {data.map((item, index) => (
          <Grid item key={index} xs={12} sm={6} md={4} lg={3}>
            <Item onClick={() => handleClickOpen(item)}>
              {item.icon}
              <Typography variant="h6">{item.title}</Typography>
            </Item>
          </Grid>
        ))}
      </Grid>
      <Dialog open={open} onClose={handleClose}>
        <DialogTitle>{selectedItem?.title}</DialogTitle>
        <DialogContent>
          <Typography variant="body1">{selectedItem?.describe}</Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleClose} color="primary">
            Close
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default BlogLink;
